name         'puppet-cassandra'
version      '0.0.1'
author       'Stephan Lohwasser'
license      'Apache 2.0'
project_page 'https://github.com/lowi-yeah/puppet-cassandra'
source       'https://github.com/lowi-yeah/puppet-cassandra'
summary      'A Wirbelsturm compatible module for managing and configuring Apache Cassandra. Forked from msimonin/puppet-cassandra.'
description  'A Wirbelsturm compatible module for managing and configuring Apache Cassandra. Forked from msimonin/puppet-cassandra.'
dependency   'puppetlabs/stdlib', '>= 3.0.0'
dependency   'puppetlabs/apt', '1.x'
